import Gallery from 'components/Gallery';
import Head from 'next/head';
import Image from 'next/image';
import Hero from 'components/Hero.jsx';
import { Wedding, Engagement } from 'components/Photos.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>LJ Photography</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='LJ Photography' message='Capturing precious moments one photo at a time.' />
      <Gallery slides={Wedding}/>
    </div>
  );
}