import Gallery from 'components/Gallery';
import Head from 'next/head';
import Image from 'next/image';
import Hero from 'components/Hero.jsx';
import { SliderData } from 'components/SliderData.js'
import Instagram from 'components/Instagram';

export default function Home() {
  return (
    <div>
      <Head>
        <title>LJ Photography</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='LJ Photography' message='Lorem ipsum dolor sit amet, consectetur adipiscing elit.' />
      <Gallery slides={SliderData}/>
      <Instagram />
    </div>
  );
}